### PR TITLE
style links as small button group

### PR DESCRIPTION
**Pull request by joshinils**
it looks like osm.org is using bootstrap, so using a bootstrap button group class

### CODE REVIEW

**Comment by kmpoppe** [comment]
Could you screenshot a before/after that change and provide it here please?

**Comment by joshinils** [comment]
imageimage

imageimage

**Comment by kmpoppe** [comment]
Thanks, looks great :)

**Review by kmpoppe — APPROVED** [review]

**Comment by joshinils** [comment]
btn-group-sm
image


btn-group-m
image

btn-group-l
image

btn-group
image

**Pull request merged**
